CN-39
VeamVeat/line_story pull request #4
Opened 2021-10-15 17:39 UTC by VeamVeat

https://trello.com/c/Z581zsnh

2021-10-17 17:25 UTC, MaxKomarenko commented on line/line/settings.py
> +    'modeltranslation',
Зачем это?

2021-10-17 19:18 UTC, VeamVeat commented on line/line/settings.py
> +    'modeltranslation',
Прочёл, есть такое приложение 'modeltranslation', которая позволяет перевести нужные поля модели, не меняя саму модель и структуру базы данных, но как я понял я сильно далеко ушёл и в текущей задаче это не нужно

2021-10-17 19:19 UTC, VeamVeat commented on line/line/settings.py
> +gettext = lambda s: s
логично, увидел

2021-10-20 19:25 UTC, MaxKomarenko requested changes

2021-10-20 19:25 UTC, MaxKomarenko commented on line/line/urls.py
> +
Лишняя строка

2021-10-20 19:25 UTC, MaxKomarenko commented on line/line/settings.py
>  import os
Нужно разделять импорты по pep8

2021-11-01 17:52 UTC, MaxKomarenko requested changes

2021-11-01 17:52 UTC, MaxKomarenko commented on line/line/settings.py
> +from django.utils.translation import ugettext_lazy as _
Пропустил комментарий

2021-11-01 17:52 UTC, MaxKomarenko commented on line/line/urls.py
> +
Пропустил комментарий

2021-11-01 17:52 UTC, MaxKomarenko commented on line/line/urls.py
> +from django.urls import path, include
include - неиспользуемый импорт

2021-11-01 17:52 UTC, MaxKomarenko commented on line/line/urls.py
>  from line import settings
Django settings нужно брать через - from django.conf import settings

Я вроде где-то это тебе писал. И здесь ошибка! Как это попало в коммит?

2021-11-01 21:28 UTC, VeamVeat commented on line/line/settings.py
> +from django.utils.translation import ugettext_lazy as _
Разделяются импорты стандартных библиотек, сторонних библиотек и импорты локального приложения, исправил

2021-11-01 21:28 UTC, VeamVeat commented on line/line/urls.py
> +
Исправил

2021-11-01 21:46 UTC, VeamVeat reviewed
Исправлено

2021-11-03 09:48 UTC, merged