CN-40
VeamVeat/line_story pull request #5
Opened 2021-10-18 15:08 UTC by VeamVeat

https://trello.com/c/q5yCkp6e

2021-10-20 19:29 UTC, MaxKomarenko commented on line/line/settings.py
> +DEBUG = True if os.getenv("DEBUG") == 'True' else False
Это параметры getenv - def getenv(key, default=None):

Почему не использовать bool(os.getenv("DEBUG"))

2021-10-20 19:33 UTC, MaxKomarenko commented on line/line/settings.py
> +                    'NAME': os.getenv("NAME"),
Я бы назвал енву DATABASE_NAME

2021-10-20 19:34 UTC, MaxKomarenko commented on line/.env
> +SECRET_KEY = 'django-insecure-+&&u628#uiwivawo*==k9u2l_wv3p1=lf-b!957avw(rgk*i(r'
Енв файл должен быть в gitignore, иначе зачем он нужен?

2021-10-20 19:35 UTC, MaxKomarenko commented on .gitignore
> +/line/.env/
По-видимому, ты неверно указал путь до файла

2021-10-21 07:35 UTC, VeamVeat commented on line/line/settings.py
> +                    'NAME': os.getenv("NAME"),
Исправил

2021-10-28 22:02 UTC, MaxKomarenko requested changes
Папка логов и медиа попала в комит, удали. 

UDP папки оставляем, фалы не тащим в гит

2021-11-02 08:36 UTC, VeamVeat reviewed
Исправлено

2021-11-02 09:25 UTC, VeamVeat reviewed
Исправлено

2021-11-02 10:21 UTC, VeamVeat reviewed
Исправлено

2021-11-02 10:21 UTC, VeamVeat commented on line/.env.example
> +DATABASE_PASSWORD = 'PASSWORD'
Исправлено

2021-11-02 10:43 UTC, VeamVeat reviewed
Исправлено

2021-11-03 10:00 UTC, MaxKomarenko requested changes

2021-11-03 10:00 UTC, MaxKomarenko commented on line/.env.example
> +DATABASE_PASSWORD =PASSWORD
NAME DB - так нельзя

2021-11-03 10:00 UTC, MaxKomarenko commented on line/.env.example
> +DATABASE_PASSWORD =PASSWORD
Я все еще вижу тут пробелы

2021-11-03 10:00 UTC, MaxKomarenko commented on line/.env.example
> +ENGINE =ENGINE
ENGINE - не нужно тащить из енвов

2021-11-03 10:00 UTC, MaxKomarenko commented on line/.env.example
> +DEBUG =STATUS
Евы лучше группировать. И группы разделять отступами. Например, если у тебя идет группа по DB, то DEBUG можно отделить

2021-11-03 10:00 UTC, MaxKomarenko commented on line/.env.example
> +NAME =NAME DB
Нейминг нужно дополнить. С точки зрения .env файла не понятно к чему относится данный NAME. Намного объективнее будет назвать его DB_NAME.

2021-11-03 10:00 UTC, MaxKomarenko commented on line/.env.example
> +NAME =NAME DB
То же касается остальных

2021-11-03 10:00 UTC, MaxKomarenko commented on line/line/settings.py
> +        'NAME': os.getenv("DATABASE_NAME"),
В env.example у тебя другие имена. Нужно не забывать синкать их

2021-11-09 14:08 UTC, merged