CN-43
VeamVeat/line_story pull request #6
Opened 2021-10-23 15:25 UTC by VeamVeat

https://trello.com/c/qBJizMt0

2021-11-01 18:20 UTC, MaxKomarenko requested changes

2021-11-01 18:20 UTC, MaxKomarenko commented on line/line/urls.py
>  from line import settings
Тут ошибка

2021-11-01 18:20 UTC, MaxKomarenko commented on line/line/urls.py
> +    path('', include('users.urls')),
Нужно выделить иерархию в ростах. Для этого все роуты для пользователя нужно вынести под /user/ в доменном имене
```suggestion
    path('users/', include('users.urls')),
```

2021-11-01 18:20 UTC, MaxKomarenko commented on line/users/admin.py
> +    filter_horizontal = ()
Где ответ на данный комментарий?

2021-11-01 18:20 UTC, MaxKomarenko commented on line/users/models.py
> +        return '%s %s' % (self.first_name, self.last_name)
Почему не используешь f-string?

2021-11-01 18:20 UTC, MaxKomarenko commented on line/users/models.py
> +    @full_name.setter
setter для full name не нужен, тк это разные поля модели. К тому же ты не вызвал тут метод save, а значит данные не сохранятся в базу.

2021-11-01 18:20 UTC, MaxKomarenko commented on line/users/models.py
> +    return 'users/image_profile/user_{0}/{1}'.format(instance.user.id, filename)
Почему не использовать f-string?

2021-11-01 18:20 UTC, MaxKomarenko commented on line/users/models.py
> +    if value < 18:
Магическая переменная 18... Не понятно, какой смысл она несет...

2021-11-01 18:20 UTC, MaxKomarenko commented on line/users/models.py
> +        default='users/image_profile/default.png',
Дефолта тут не должно быть

2021-11-01 18:20 UTC, MaxKomarenko commented on line/users/models.py
> +    image = models.ImageField(
Тут должна быть связь с модели Files

2021-11-01 18:20 UTC, MaxKomarenko commented on line/users/models.py
> +        Wallet.objects.create(user=instance)
Добавь сюда корзину

2021-11-01 18:20 UTC, MaxKomarenko commented on line/users/models.py
> +    instance.wallet.save()
Зачем каждый раз их сохранять?

2021-11-02 12:01 UTC, VeamVeat reviewed
Исправлено

2021-11-02 12:01 UTC, VeamVeat commented on line/users/models.py
> +        Wallet.objects.create(user=instance)
Исправлено

2021-11-02 12:45 UTC, VeamVeat reviewed
Исправлено

2021-11-03 10:40 UTC, MaxKomarenko requested changes
В ходе работы над одним коммитом ты создал несколько миграций в которых ты модифицировал свои решения. Лучше так не делать. По окончании работы, нужно удалить все новые (те миграции, которые были созданы в рамках работы над новым коммитом) миграции сделать одну. С точки зрения проекта, вся работа проделанная в рамках одного коммита это одна итерация апдейта данных, поэтому давай миграции приводить к тому же виду.

2021-11-03 10:40 UTC, MaxKomarenko commented on line/users/models.py
> +from django.core.exceptions import ObjectDoesNotExist, ValidationError
ObjectDoesNotExist - не используется здесь

2021-11-03 10:40 UTC, MaxKomarenko commented on line/users/models.py
> +from orders.models import Cart
Я так понял, что ты добавил их тк в данный момент этих моделей нет. В таком случае нужно сделать эти строки комментариями с пометкой todo и текстом - описание по какой причине так нужно здесь сделать.

А без этого ты пытаешь добавить код с ошибкой. Ни одна сборка с этим не соберется.

```suggestion
# from orders.models import Cart todo раскомментировать, когда будут добавлено приложение orders (CN-46)
```

Для всех мест использования этих переменных можно сделать тоже самое. Все связи с таблицами в БД можно пока закоментить и выкатить вместе с добавлением приложений.

Кстати, это пример того какие комменты можно заливать в гит. Можно кстати в комментарии указать номер задачи. Чтобы был понятен контекст если что.

2021-11-03 10:40 UTC, MaxKomarenko commented on line/users/models.py
> +def save_profile_and_wallet(sender, instance, **kwargs):
Удалил сохранение wallet, а название не изменил. Будь внимательнее плз.

2021-11-03 10:40 UTC, MaxKomarenko commented on line/users/models.py
> +    instance.profile.save()
Зачем здесь это? Жду ответ на вопрос до того, как ты попытаешься это удалить :)

2021-11-03 13:31 UTC, VeamVeat reviewed
Исправлено

2021-11-03 13:31 UTC, VeamVeat commented on line/users/models.py
> +from orders.models import Cart
Исправлено

2021-11-03 13:31 UTC, VeamVeat commented on line/users/models.py
> +def save_profile_and_wallet(sender, instance, **kwargs):
Исправлено

2021-11-03 13:31 UTC, VeamVeat commented on line/users/models.py
> +    instance.profile.save()
Нужен для обновления пользователя и профиля за один вызов. Например если мы изменяем user и profile:
user.last_name = 'Vadim'
user.profile.age = 22
и теперь вызываем user.save() вместо user.profile.save()

2021-11-03 14:05 UTC, VeamVeat reviewed
Исправлено

2021-11-09 14:54 UTC, merged