CN-46
VeamVeat/line_story pull request #7
Opened 2021-10-27 14:49 UTC by VeamVeat

https://trello.com/c/SyLuDZUf

2021-11-02 12:12 UTC, VeamVeat reviewed
Исправлено

2021-11-03 12:17 UTC, MaxKomarenko requested changes

2021-11-03 12:17 UTC, MaxKomarenko commented on line/products/menagers.py
> +class PersonQuerySet(models.QuerySet):
Фильтры не нужно выносить в менеджер модели. Фильтры легко выполнить в коде. В менеджер модели нужно выносить сложные конструкции типа составных аннотаций или группировок и тд...

2021-11-03 12:17 UTC, MaxKomarenko commented on line/products/models.py
> +    product_type = models.ForeignKey(ProductType, models.CASCADE)
Аналогично для каскада.

2021-11-03 12:17 UTC, MaxKomarenko commented on line/orders/models.py
> +    product = models.ManyToManyField(Product, models.CASCADE)
И опять же, если удалится продукты, то будет удалена корзина. Вроде как, нужно прочекать.

2021-11-03 12:17 UTC, MaxKomarenko commented on .gitignore
> +/log/
Логи это тоже часть проекта, лучше внести их в папку line

2021-11-03 20:07 UTC, VeamVeat reviewed
Исправлено

2021-11-03 20:07 UTC, VeamVeat commented on line/products/models.py
> +    size = models.CharField(max_length=10, verbose_name=_('size of file'))
Исправлено

2021-11-22 16:03 UTC, MaxKomarenko requested changes

2021-11-22 16:31 UTC, MaxKomarenko approved these changes

2021-11-22 16:31 UTC, merged