CN-47
VeamVeat/line_story pull request #8
Opened 2021-11-09 16:28 UTC by VeamVeat

https://trello.com/c/0ItGAGhb

2021-11-22 17:19 UTC, MaxKomarenko requested changes

2021-11-22 17:19 UTC, MaxKomarenko commented on line/users/tokens.py
> +class AccountActivationTokenGenerator(PasswordResetTokenGenerator):
Непонятно зачем это нужно. Лучше юзать встроенный метод.

2021-11-22 17:19 UTC, MaxKomarenko commented on line/line/settings.py
> +EMAIL_HOST = os.getenv("EMAIL_HOST")
Сделай при debug=True вывод сообщений в консоль

2021-11-23 12:30 UTC, VeamVeat reviewed
Исправлено

2021-11-24 07:54 UTC, MaxKomarenko commented on line/users/views.py
> +from django.utils.translation import ugettext_lazy as _
Не исправлено

2021-11-24 08:01 UTC, MaxKomarenko requested changes

2021-11-24 08:01 UTC, MaxKomarenko commented on line/users/views.py
> +        if user is not None and tokens.default_token_generator.check_token(user, token):
Можно заменить на 

```suggestion
        if user and tokens.default_token_generator.check_token(user, token):
```

2021-12-01 09:40 UTC, MaxKomarenko requested changes
При восстановлении пароля генерируя неверная ссылка - ://127.0.0.1:8000/activate/Mg/awz0rr-6ed173d17176a56647628c0a733df69f/

При переходе по ссылке на восстановление пароля, открывается страница **Welcome to my website**, а не форма с заполнением новых полей

2021-12-01 09:40 UTC, MaxKomarenko commented on line/users/templates/users/register.html
> +{% block content %}l
Тут лишняя буква **l**

2021-12-01 09:48 UTC, merged